services:
  qlogix:
    image: ghcr.io/qmaru/qlogix:latest
    environment:
      QLOGIX_CONFIG: /app/config.toml
      TZ: Asia/Shanghai
    volumes:
      - ./config.toml:/app/config.toml:ro
    profiles:
      - cli
